/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#b0c6ff',
        'on-primary-fixed-variant': '#244485',
        'on-surface': '#1a1c1e',
        'secondary-container': '#68abff',
        'inverse-on-surface': '#f0f0f3',
        'on-background': '#1a1c1e',
        'surface-container-high': '#e8e8ea',
        'outline': '#747781',
        'on-error-container': '#93000a',
        'primary-fixed': '#d9e2ff',
        'on-secondary': '#ffffff',
        'on-tertiary-container': '#92969b',
        'on-primary-container': '#7895da',
        'surface-container': '#eeeef0',
        'on-secondary-fixed': '#001c39',
        'surface-container-lowest': '#ffffff',
        'surface-tint': '#3f5c9e',
        'outline-variant': '#c4c6d2',
        'surface-bright': '#f9f9fc',
        'on-primary': '#ffffff',
        'on-surface-variant': '#444650',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-secondary-fixed-variant': '#004883',
        'tertiary-container': '#2a2f33',
        'tertiary-fixed-dim': '#c3c7cc',
        'on-secondary-container': '#003e73',
        'error': '#ba1a1a',
        'surface-variant': '#e2e2e5',
        'secondary': '#0060ac',
        'secondary-fixed-dim': '#a4c9ff',
        'on-primary-fixed': '#001945',
        'on-tertiary': '#ffffff',
        'surface-container-highest': '#e2e2e5',
        'primary-container': '#002b6b',
        'primary-fixed-dim': '#b0c6ff',
        'surface': '#f9f9fc',
        'inverse-surface': '#2f3133',
        'secondary-fixed': '#d4e3ff',
        'primary': '#001842',
        'on-tertiary-fixed-variant': '#42474b',
        'background': '#f9f9fc',
        'surface-container-low': '#f3f3f6',
        'tertiary': '#151a1e',
        'tertiary-fixed': '#dfe3e8',
        'surface-dim': '#dadadc',
        'on-tertiary-fixed': '#171c20',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'container-max': '1280px',
        base: '8px',
        gutter: '24px',
        'margin-desktop': '64px',
        'margin-mobile': '20px',
        'section-padding': '120px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        'body-md': ['Inter', 'system-ui', 'sans-serif'],
        'headline-lg': ['Hanken Grotesk', 'Inter', 'sans-serif'],
        'headline-xl': ['Hanken Grotesk', 'Inter', 'sans-serif'],
        'button': ['Hanken Grotesk', 'Inter', 'sans-serif'],
        'headline-lg-mobile': ['Hanken Grotesk', 'Inter', 'sans-serif'],
        'label-sm': ['JetBrains Mono', 'monospace'],
        'body-lg': ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'button': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
